In [7]:
import numpy as np
a= np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
row_r1 = a[1, :]
row_r2 = a[1:2, :]
row_r3 = a[[1], :]
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)
print(row_r3, row_r3.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[[5 6 7 8]] (1, 4)


In [17]:
import numpy as np
b = np.zeros((2,2))
print(b)

[[0. 0.]
 [0. 0.]]


In [23]:
x= np.ones((1,2))
print(x)

[[1. 1.]]


In [31]:
c= np.full((2,2), 4)
print(c)

[[4 4]
 [4 4]]


In [27]:
d= np.eye(2)
print(d)
print(d.dtype)

[[1. 0.]
 [0. 1.]]
float64


In [29]:
e= np.random.random((2,2))
print(e)

[[0.7843256  0.86378796]
 [0.35279147 0.29310894]]


In [33]:
a= np.array([1,2,3])
b= np.array([4,5,6])
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
a= np.array([1,2,3])
b= np.array([4,5,6])
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [47]:
x= np.array([[1,2],[3,4]], dtype=np.float64)
y= np.array([[5,6],[7,8]], dtype=np.float64)
print(x+y)
print(np.add(x, y))
print(np.subtract(x, y))
print(np.multiply(x,y))
print(np.divide(x,y))
print(np.sqrt(x))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]
