In [21]:
import numpy as np
x= np.array([[1,2],[3,4]])
y= np.array([[5,6],[7,8]])

v= np.array([9,10])
w= np.array([11,12])

m= np.array([[1,2,3],[4,5,6],[7,8,9]])
n= np.array([[9,8,7],[6,5,4],[3,2,1]])

print(x.dot(y))
print(np.dot(v,w))
print(np.dot(m,n))
print(x@y)
print(y@x)
print(np.cross(m,n))
print(np.cross(x,y))

[[19 22]
 [43 50]]
219
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
[[19 22]
 [43 50]]
[[23 34]
 [31 46]]
[[-10  20 -10]
 [-10  20 -10]
 [-10  20 -10]]
[-4 -4]


In [37]:
import numpy as np
preds = np.array([0.2,0.5,0.92,0.9,0.1])
predicted_class_index= np.argmax(preds)
predicted_class_index

to_predict_class= ["apple", "banana", "ball", "mango", "orange"]
possible_class_index = np.where(preds>0.85)[0]

for possible_class_index in possible_class_indexs:
   print(to_predict_class[possible_class_index])

NameError: name 'possible_class_indexs' is not defined

In [51]:
a= np.array([1,8,9,-3,2,4,7,9])
print(np.argmax(a))
print(np.argmin(a))
print(np.argsort(a))
print(np.argsort(a)[::-1])
print(np.where(a>5))
#print(np.where(a>5))[0]

2
3
[3 0 4 5 6 1 2 7]
[7 2 1 6 5 4 0 3]
(array([1, 2, 6, 7], dtype=int64),)


In [53]:
x= np.array([[1,2],[3,4],[5,6]])
print(np.max(x))
print(np.min(x))
print(np.sum(x))


6
1
21


In [55]:
data= np.array([1,2])
data.T

array([1, 2])

In [57]:
x=np.array([[1,2],[3,4],[5,6]])
print(x)
print("transpose\n",x.T)

[[1 2]
 [3 4]
 [5 6]]
transpose
 [[1 3 5]
 [2 4 6]]


In [2]:
import numpy as np
data = np.array([1,2,3,4,5,6,7,8])
data.shape(2,4)


TypeError: 'tuple' object is not callable

In [12]:
data = np.array([1,2,3,4,5,6,7,8])
data.reshape(4,4)

ValueError: cannot reshape array of size 8 into shape (4,4)

In [8]:
data = np.array([1,2,3,4,5,6,7,8])
data.reshape(2,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [14]:
w=np.array([[1],[2],[3]])
print(w)
w.shape

[[1]
 [2]
 [3]]


(3, 1)

In [32]:
y= w.reshape(-1,)
print(y)
y.shape

[1 2 3]


(3,)

In [34]:
w= np.array([[1],[2],[3]])
z=w.squeeze()
print(z)
z.shape

[1 2 3]


(3,)

In [38]:
arr=np.array([[1,2,3]])
print(arr.shape)

squeezed_arr= np.squeeze(arr)
print(squeezed_arr.shape)
print(squeezed_arr)

(1, 3)
(3,)
[1 2 3]


In [42]:
arr= np.array([[[1],[2]]])
print(arr.shape)
squeezed_arr= np.squeeze(arr)
print(squeezed_arr.shape)
print(squeezed_arr)

(1, 2, 1)
(2,)
[1 2]


In [52]:
y=np.array([1,2])
print(y.ndim)
y= y.reshape((-1,1,1)) 
print(y.ndim)


1
3
