In [2]:
import numpy as np

In [16]:
x= np.array([2,4,6,3,8,15])
print(x)

[ 2  4  6  3  8 15]


In [15]:
np.sum()
np.prod()

np.min()
np.max()

np.mean()
np.std()
np.median()
np.sort()

TypeError: sum() missing 1 required positional argument: 'a'

In [8]:
sum= np.sum(x)
print(sum)

17


In [12]:
median= np.median(x)
print(median)

3.5


In [14]:
print(np.sort(x))

[2 3 4 6]


In [18]:
print(x[1])

4


In [20]:
print(x[-1:-3])

[]


In [22]:
print(x[5:])

[15]


In [38]:
y=x[:2].copy()
print(y)

[2 4]


In [32]:
print(x)

[ 2  4  6  3  8 15]


In [39]:
print(y)

[2 4]


In [41]:
print(x[0:6:2])

[2 6 8]


In [42]:
print(x[-1::-1])

[15  8  3  6  4  2]
