In [3]:
import numpy as np
data = np.array([1,2,3,4,5,6,7,8])
data.reshape(2,4)


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [5]:
#broadcasting
a=np.array([1,2,3])
print(a)

b=np.array([[4],[5],[6]])
print(b)

c= a+b
print(c)

[1 2 3]
[[4]
 [5]
 [6]]
[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [19]:
a= np.array([[[1,2,3,4,5],[2,6,7,8,8],[4,6,7,7,6],[3,7,8,5, 7]], [[1,2,3,4,5],[2,6,7,8,8],[4,6,7,7,6],[3,7,8,5, 7]]])
print(a)

b= np.array([[2,3],[4,7]])
print(b)

#c= a+b



[[[1 2 3 4 5]
  [2 6 7 8 8]
  [4 6 7 7 6]
  [3 7 8 5 7]]

 [[1 2 3 4 5]
  [2 6 7 8 8]
  [4 6 7 7 6]
  [3 7 8 5 7]]]
[[2 3]
 [4 7]]


In [35]:
A= np.array([[1,2,3,8],[2,6,7,7],[4,6,7,5],[4,0,7,5]])
det_A = np.linalg.det(A)
print("Determinant of A:", det_A)

Determinant of A: 431.9999999999998


In [45]:
#linear equation solve
A= np.array([[3,1,-2],[2,-1,1],[1,2,3]])
print(A)
b= np.array([9,3,12])

solution = np.linalg.solve(A,b)
print(solution)

[[ 3  1 -2]
 [ 2 -1  1]
 [ 1  2  3]]
[2.6 3.2 1. ]


In [51]:
#random number
random_number = np.random.rand(5)
print(random_number)

random_array_2d= np.random.rand(3,3)
print(random_array_2d)


[0.33623665 0.55334393 0.37307683 0.37895719 0.61392249]
[[0.05274971 0.05777852 0.28294472]
 [0.09103475 0.65238474 0.14246475]
 [0.01764593 0.1671053  0.84958084]]


In [57]:
random_int_array= np.random.randint(0,10, size=5)
print(random_int_array)

random_int_array2d= np.random.randint(0,10, size=(3,2))
print(random_int_array2d)

[5 2 0 5 7]
[[1 6]
 [0 6]
 [9 2]]


In [73]:
random_sample_with_replacement = np.random.choice([1,2,3,4,5], size=3, replace=False)
print(random_sample_with_replacement)

[2 1 4]


In [67]:
np.random.seed(42)